/* winit → keyboard_types conversion for WebView input (compact keyutils). */

use keyboard_types::{Code, Key, KeyState, KeyboardEvent, Location, Modifiers, NamedKey};
use winit::event::KeyEvent;
use winit::keyboard::{KeyCode as WinitCode, KeyLocation as WinitLocation, PhysicalKey};

fn code_from_winit(code: PhysicalKey) -> Code {
    match code {
        PhysicalKey::Code(c) => match c {
            WinitCode::Backquote => Code::Backquote,
            WinitCode::Backslash => Code::Backslash,
            WinitCode::BracketLeft => Code::BracketLeft,
            WinitCode::BracketRight => Code::BracketRight,
            WinitCode::Comma => Code::Comma,
            WinitCode::Digit0 => Code::Digit0,
            WinitCode::Digit1 => Code::Digit1,
            WinitCode::Digit2 => Code::Digit2,
            WinitCode::Digit3 => Code::Digit3,
            WinitCode::Digit4 => Code::Digit4,
            WinitCode::Digit5 => Code::Digit5,
            WinitCode::Digit6 => Code::Digit6,
            WinitCode::Digit7 => Code::Digit7,
            WinitCode::Digit8 => Code::Digit8,
            WinitCode::Digit9 => Code::Digit9,
            WinitCode::Equal => Code::Equal,
            WinitCode::KeyA => Code::KeyA,
            WinitCode::KeyB => Code::KeyB,
            WinitCode::KeyC => Code::KeyC,
            WinitCode::KeyD => Code::KeyD,
            WinitCode::KeyE => Code::KeyE,
            WinitCode::KeyF => Code::KeyF,
            WinitCode::KeyG => Code::KeyG,
            WinitCode::KeyH => Code::KeyH,
            WinitCode::KeyI => Code::KeyI,
            WinitCode::KeyJ => Code::KeyJ,
            WinitCode::KeyK => Code::KeyK,
            WinitCode::KeyL => Code::KeyL,
            WinitCode::KeyM => Code::KeyM,
            WinitCode::KeyN => Code::KeyN,
            WinitCode::KeyO => Code::KeyO,
            WinitCode::KeyP => Code::KeyP,
            WinitCode::KeyQ => Code::KeyQ,
            WinitCode::KeyR => Code::KeyR,
            WinitCode::KeyS => Code::KeyS,
            WinitCode::KeyT => Code::KeyT,
            WinitCode::KeyU => Code::KeyU,
            WinitCode::KeyV => Code::KeyV,
            WinitCode::KeyW => Code::KeyW,
            WinitCode::KeyX => Code::KeyX,
            WinitCode::KeyY => Code::KeyY,
            WinitCode::KeyZ => Code::KeyZ,
            WinitCode::Minus => Code::Minus,
            WinitCode::Period => Code::Period,
            WinitCode::Quote => Code::Quote,
            WinitCode::Semicolon => Code::Semicolon,
            WinitCode::Slash => Code::Slash,
            WinitCode::Backspace => Code::Backspace,
            WinitCode::Enter => Code::Enter,
            WinitCode::Space => Code::Space,
            WinitCode::Tab => Code::Tab,
            WinitCode::Delete => Code::Delete,
            WinitCode::End => Code::End,
            WinitCode::Home => Code::Home,
            WinitCode::Insert => Code::Insert,
            WinitCode::PageDown => Code::PageDown,
            WinitCode::PageUp => Code::PageUp,
            WinitCode::ArrowDown => Code::ArrowDown,
            WinitCode::ArrowLeft => Code::ArrowLeft,
            WinitCode::ArrowRight => Code::ArrowRight,
            WinitCode::ArrowUp => Code::ArrowUp,
            WinitCode::Escape => Code::Escape,
            WinitCode::F1 => Code::F1,
            WinitCode::F2 => Code::F2,
            WinitCode::F3 => Code::F3,
            WinitCode::F4 => Code::F4,
            WinitCode::F5 => Code::F5,
            WinitCode::F6 => Code::F6,
            WinitCode::F7 => Code::F7,
            WinitCode::F8 => Code::F8,
            WinitCode::F9 => Code::F9,
            WinitCode::F10 => Code::F10,
            WinitCode::F11 => Code::F11,
            WinitCode::F12 => Code::F12,
            WinitCode::AltLeft => Code::AltLeft,
            WinitCode::AltRight => Code::AltRight,
            WinitCode::ControlLeft => Code::ControlLeft,
            WinitCode::ControlRight => Code::ControlRight,
            WinitCode::ShiftLeft => Code::ShiftLeft,
            WinitCode::ShiftRight => Code::ShiftRight,
            WinitCode::SuperLeft => Code::MetaLeft,
            WinitCode::SuperRight => Code::MetaRight,
            _ => Code::Unidentified,
        },
        PhysicalKey::Unidentified(_) => Code::Unidentified,
    }
}

fn key_from_winit(key: &winit::keyboard::Key) -> Key {
    match key {
        winit::keyboard::Key::Character(c) => Key::Character(c.to_string()),
        winit::keyboard::Key::Named(named) => match named {
            winit::keyboard::NamedKey::Enter => Key::Named(NamedKey::Enter),
            winit::keyboard::NamedKey::Tab => Key::Named(NamedKey::Tab),
            winit::keyboard::NamedKey::Backspace => Key::Named(NamedKey::Backspace),
            winit::keyboard::NamedKey::Escape => Key::Named(NamedKey::Escape),
            winit::keyboard::NamedKey::Delete => Key::Named(NamedKey::Delete),
            winit::keyboard::NamedKey::Space => Key::Character(" ".into()),
            winit::keyboard::NamedKey::ArrowDown => Key::Named(NamedKey::ArrowDown),
            winit::keyboard::NamedKey::ArrowLeft => Key::Named(NamedKey::ArrowLeft),
            winit::keyboard::NamedKey::ArrowRight => Key::Named(NamedKey::ArrowRight),
            winit::keyboard::NamedKey::ArrowUp => Key::Named(NamedKey::ArrowUp),
            winit::keyboard::NamedKey::Home => Key::Named(NamedKey::Home),
            winit::keyboard::NamedKey::End => Key::Named(NamedKey::End),
            winit::keyboard::NamedKey::PageUp => Key::Named(NamedKey::PageUp),
            winit::keyboard::NamedKey::PageDown => Key::Named(NamedKey::PageDown),
            winit::keyboard::NamedKey::F1 => Key::Named(NamedKey::F1),
            winit::keyboard::NamedKey::F2 => Key::Named(NamedKey::F2),
            winit::keyboard::NamedKey::F3 => Key::Named(NamedKey::F3),
            winit::keyboard::NamedKey::F4 => Key::Named(NamedKey::F4),
            winit::keyboard::NamedKey::F5 => Key::Named(NamedKey::F5),
            winit::keyboard::NamedKey::F6 => Key::Named(NamedKey::F6),
            winit::keyboard::NamedKey::F7 => Key::Named(NamedKey::F7),
            winit::keyboard::NamedKey::F8 => Key::Named(NamedKey::F8),
            winit::keyboard::NamedKey::F9 => Key::Named(NamedKey::F9),
            winit::keyboard::NamedKey::F10 => Key::Named(NamedKey::F10),
            winit::keyboard::NamedKey::F11 => Key::Named(NamedKey::F11),
            winit::keyboard::NamedKey::F12 => Key::Named(NamedKey::F12),
            _ => Key::Named(NamedKey::Unidentified),
        },
        winit::keyboard::Key::Dead(_) => Key::Named(NamedKey::Dead),
        _ => Key::Named(NamedKey::Unidentified),
    }
}

fn location_from_winit(location: WinitLocation) -> Location {
    match location {
        WinitLocation::Left => Location::Left,
        WinitLocation::Right => Location::Right,
        WinitLocation::Numpad => Location::Numpad,
        WinitLocation::Standard => Location::Standard,
        _ => Location::Standard,
    }
}

pub fn keyboard_event_from_winit(
    event: &KeyEvent,
    modifiers: Modifiers,
) -> KeyboardEvent {
    let state = match event.state {
        winit::event::ElementState::Pressed => KeyState::Down,
        winit::event::ElementState::Released => KeyState::Up,
    };
    KeyboardEvent {
        state,
        code: code_from_winit(event.physical_key),
        key: key_from_winit(&event.logical_key),
        location: location_from_winit(event.location),
        modifiers,
        repeat: event.repeat,
        is_composing: false,
    }
}
