#!/usr/bin/env bash
# brow — AppImage builder (Phase 5)
#
# Produces a portable linux x86_64 AppImage from the SAME staged payload the
# .deb/.rpm consume. The engine binary and its resources are installed under
# AppDir/usr/lib/brow (resources resolve relative to the binary), a relative
# symlink exposes it at AppDir/usr/bin/brow, and a custom AppRun wires
# LD_LIBRARY_PATH to the libs linuxdeploy bundles from ldd.
#
# Works headless: linuxdeploy runs with APPIMAGE_EXTRACT_AND_RUN=1 so no FUSE
# is needed inside CI containers.
#
# Usage:
#   ./build-appimage.sh --payload <dir> --version <v> [--out <dir>] \
#                      [--skip-download]   # reuse cached linuxdeploy
#
# Env overrides:
#   LINUXDEPLOY_URL   full URL of the linuxdeploy AppImage
#                     (default: continuous build; pin a dated release tag for
#                      fully reproducible CI and set this var)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PAYLOAD_DIR=""
VERSION=""
OUT_DIR=""
SKIP_DOWNLOAD=0
LINUXDEPLOY_URL="${LINUXDEPLOY_URL:-https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --payload)       PAYLOAD_DIR="$2"; shift 2 ;;
    --version)       VERSION="$2"; shift 2 ;;
    --out)           OUT_DIR="$2"; shift 2 ;;
    --skip-download) SKIP_DOWNLOAD=1; shift ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

[[ -n "$PAYLOAD_DIR" && -n "$VERSION" ]] || {
  echo "error: --payload and --version are required" >&2; exit 2; }
[[ -x "$PAYLOAD_DIR/brow" ]] || {
  echo "error: payload missing executable: $PAYLOAD_DIR/brow" >&2; exit 2; }
[[ -d "$PAYLOAD_DIR/resources" ]] || {
  echo "error: payload missing resources dir" >&2; exit 2; }

OUT_DIR="${OUT_DIR:-$SCRIPT_DIR/dist}"
# Resolve early: later steps `cd` into a temp dir for the extract check.
OUT_DIR="$(cd "$OUT_DIR" && pwd)"
mkdir -p "$OUT_DIR"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
APPDIR="$WORK/brow.AppDir"

# ---- AppDir layout ----------------------------------------------------------
mkdir -p "$APPDIR/usr/lib/brow" "$APPDIR/usr/bin" \
         "$APPDIR/usr/share/applications" \
         "$APPDIR/usr/share/icons/hicolor/256x256/apps"

install -m 0755 "$PAYLOAD_DIR/brow" "$APPDIR/usr/lib/brow/brow"
cp -R "$PAYLOAD_DIR/resources" "$APPDIR/usr/lib/brow/resources"
# brow (v0.6.1): fallback binary + bundled Noto UI fonts (Arabic).
if [[ -f "$PAYLOAD_DIR/brow-classic" ]]; then
  install -m 0755 "$PAYLOAD_DIR/brow-classic" "$APPDIR/usr/lib/brow/brow-classic"
fi
if [[ -d "$PAYLOAD_DIR/fonts" ]]; then
  cp -R "$PAYLOAD_DIR/fonts" "$APPDIR/usr/lib/brow/fonts"
fi
ln -s ../lib/brow/brow "$APPDIR/usr/bin/brow"

install -m 0644 "$SCRIPT_DIR/brow.desktop" "$APPDIR/usr/share/applications/brow.desktop"
install -m 0644 "$SCRIPT_DIR/../icons/brow_256.png" \
  "$APPDIR/usr/share/icons/hicolor/256x256/apps/brow.png"

# ---- custom AppRun ----------------------------------------------------------
# We install the real ELF under usr/lib/brow (so resources/ sits beside it and
# relative resource resolution works), therefore the stock AppRun — which
# expects the executable at usr/bin — does not fit. This AppRun points at the
# real binary and exposes the libs linuxdeploy bundled into usr/lib.
# NOTE: --custom-apprun must reference a path OUTSIDE the AppDir; linuxdeploy
# copies the file into place itself (self-copy errors otherwise).
cat > "$WORK/AppRun" <<'EOF'
#!/bin/sh
# brow AppRun — generated by packaging/linux/build-appimage.sh
HERE="$(dirname "$(readlink -f "$0")")"
export LD_LIBRARY_PATH="${HERE}/usr/lib:${LD_LIBRARY_PATH:-}"
exec "${HERE}/usr/lib/brow/brow" "$@"
EOF
chmod 0755 "$WORK/AppRun"

# ---- linuxdeploy -------------------------------------------------------------
TOOL_DIR="$WORK/tool"
mkdir -p "$TOOL_DIR"
LINUXDEPLOY="$TOOL_DIR/linuxdeploy-x86_64.AppImage"
if [[ "$SKIP_DOWNLOAD" -eq 1 && -f "$HOME/.cache/brow/linuxdeploy-x86_64.AppImage" ]]; then
  cp "$HOME/.cache/brow/linuxdeploy-x86_64.AppImage" "$LINUXDEPLOY"
else
  echo "fetching linuxdeploy: $LINUXDEPLOY_URL"
  curl -fsSL --retry 3 -o "$LINUXDEPLOY" "$LINUXDEPLOY_URL"
  mkdir -p "$HOME/.cache/brow"
  cp "$LINUXDEPLOY" "$HOME/.cache/brow/linuxdeploy-x86_64.AppImage"
fi
chmod 0755 "$LINUXDEPLOY"

export ARCH=x86_64
export APPIMAGE_EXTRACT_AND_RUN=1
export OUTPUT="brow-${VERSION}-x86_64.AppImage"

# ldd scans the real ELF; desktop-file Exec is rewritten to the AppImage path;
# --custom-apprun keeps our usr/lib/brow layout intact.
"$LINUXDEPLOY" \
  --appdir "$APPDIR" \
  --executable "$APPDIR/usr/lib/brow/brow" \
  --desktop-file "$APPDIR/usr/share/applications/brow.desktop" \
  --icon-file "$SCRIPT_DIR/../icons/brow_256.png" \
  --custom-apprun "$WORK/AppRun" \
  --output appimage

ARTIFACT="$PWD/$OUTPUT"
[[ -f "$OUTPUT" ]] || { echo "error: AppImage was not produced" >&2; exit 1; }
mv "$OUTPUT" "$OUT_DIR/"
echo "wrote $OUT_DIR/$OUTPUT"

# ---- integrity smoke test ----------------------------------------------------
# Headless validation: extract the squashfs and assert the payload landed.
CHECK="$WORK/extract"
mkdir -p "$CHECK"
( cd "$CHECK" && "$OUT_DIR/$OUTPUT" --appimage-extract >/dev/null )
test -x "$CHECK/squashfs-root/usr/lib/brow/brow"
test -f "$CHECK/squashfs-root/usr/lib/brow/resources/easylist.txt"
test -f "$CHECK/squashfs-root/usr/share/applications/brow.desktop"
echo "appimage integrity check passed (binary + resources + desktop entry)"
